# PureChatExtention by Thunder33345
#avaliable tags:
#setting name: prefix, suffix1 suffix2
#economyapi: ecoapi, mymoney
#faction: name, rank, power
#facpe: name, rank, ppower, ppowerl, fpower, fpowerl, fbank
tags: #Tags to enable *not case sensetive
- "EconomyAPI"
- "Faction"
faction:
  type: "GenericOld"
  plugin_name: "FactionsPro" #faction pugin's name (leave it if you dont know
  name:
    none: "" #when not in faction
    exist: "%name%" #when in faction, %name% gets replaced with faction name
  rank:
    none: ""
    member: "-"
    officer: "*"
    leader: "^"
  power:
    none: ""
    exist: "%power%"
factionspe:
  name:
    none: "-" #when not in faction
    exist: "%name%" #when in faction, %name% gets replaced with faction name
  rank:
    none: "%"
    recruit: "-"
    member: "+"
    officer: "*"
    leader: "^"
  power:
    none: "-"
    power: "%power%"
  power:
    none: "-"
    bank: "%bank%"